### ISSUE TITLE
[🐛] server readme is not pertinent

### ISSUE THREAD

**Issue by joesaraceno** [troup-io/troup-server#13]
#### Describe the bug
The readme for the server refer to the description of the client application.

#### Expected behaviour
The readme for the server should explain the server tech, lang, and goals; not a copy paste of the client readme.

#### Screenshot
![Screenshot_20200603-071522](https://user-images.githubusercontent.com/45146247/83640961-196e5900-a56a-11ea-9e16-8c3372d49491.png)

**Comment by samrith-s** [comment]
Hey @joesaraceno thanks for this. I have updated the file to reflect the changes. 😄 

Thanks for identifying it!
